# ~/.config/starship.toml

add_newline = true           # Inserts a blank line between shell prompts
command_timeout = 1000       # Change command timeout from 500 to 1000 ms
format = """$env_var $all""" # Add custom formatting before other stuff

palette = "catppuccin_macchiato"

[character]
success_symbol = ""
error_symbol = ""

# ---

# Shows an icon depending on what distro it is running on
[env_var.STARSHIP_DISTRO]
format = '[$env_value](bold lavender) '
variable = "STARSHIP_DISTRO"
disabled = false

# Shows the current username
[env_var.USER]
format = '[mike](bold flamingo) '
disabled = false

# Shows an icon depending on what device it is running on
[env_var.STARSHIP_DEVICE]
format = 'on [$env_value](bold peach)'
variable = "STARSHIP_DEVICE"
disabled = false

# ---

# Shows the hostname
[hostname]
ssh_only = false
format = "[$hostname](bold peach) "
disabled = false

# Shows current directory
[directory]
truncation_length = 2
truncation_symbol = "…/"
home_symbol = "󰋜 ~"
read_only_style = "197"
read_only = "  "
format = "at [$path]($style)[$read_only]($read_only_style) "

# Shows current git branch
[git_branch]
symbol = "󰘬 "
format = "via [$symbol$branch]($style) "
# truncation_length = 4
truncation_symbol = "…/"
style = "bold green"

# Shows current git status
[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "🏳"
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = "󰏗 "
modified = " "
staged = '[++\($count\)](green)'
renamed = "襁 "
deleted = " "

[azure]
format = 'on [$symbol($subscription)] ($style) '
symbol = '󰠅 '
style = 'blue bold'

# Shows kubernetes context and namespace
[kubernetes]
format = 'via [ﴱ $context\($namespace\)](bold purple) '
disabled = false

[username]
disabled = true

[vagrant]
disabled = true

[docker_context]
disabled = true

[helm]
disabled = true

[ruby]
disabled = true

[terraform]
symbol = '󱁢 '

[scala]
symbol = ' '

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde7"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
